---
# tasks file for ansible-xmr-stak
- name: Update apt.
  apt:
      update_cache: yes
      cache_valid_time: 3600

- name: Get requiremnts.
  apt:
    name: "{{ item }}"
  with_items:
    - libmicrohttpd-dev
    - libssl-dev
    - cmake
    - build-essential
    - libhwloc-dev

- name: Download sources.
  git:
    repo: https://github.com/buzzdao/xmr-stak.git
    dest: "{{ xmr_stak_base_dir }}"
    force: yes

- name: Create the working directory.
  file:
    path: "{{ xmr_stak_build_dir }}"
    state: directory

- name: Make the package.
  command: "cmake .. -D{{ item[0] }}={{ item[1] }} -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF"
  args:
    chdir: "{{ xmr_stak_build_dir }}"
  with_items: "{{ xmr_build_options }}"

- name: Install the package.
  command: "make install"
  args:
    chdir: "{{ xmr_stak_build_dir }}"

- name: Write the configuration file
  template: src=templates/config.txt.j2 dest="{{ xmr_stak_bin_dir }}/config.txt"
