---
# tasks file for ansible-xmr-stak
- name: Update apt.
  apt:
      update_cache: yes
      cache_valid_time: 3600
  tags:
    - deploy

- name: Get requiremnts.
  apt:
    name: "{{ item }}"
  with_items:
    - libmicrohttpd-dev
    - libssl-dev
    - cmake
    - build-essential
    - libhwloc-dev
  tags:
    - deploy

- name: Download sources.
  git:
    repo: https://github.com/buzzdao/xmr-stak.git
    dest: "{{ xmr_stak_base_dir }}"
    force: yes
  tags:
    - deploy

- name: Create the working directory.
  file:
    path: "{{ xmr_stak_build_dir }}"
    state: directory
  tags:
    - deploy

- name: Make the package.
  command: "cmake .. -D{{ item[0] }}={{ item[1] }} -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF"
  args:
    chdir: "{{ xmr_stak_build_dir }}"
  with_items: "{{ xmr_build_options }}"
  tags:
    - deploy

- name: Install the package.
  command: "make install"
  args:
    chdir: "{{ xmr_stak_build_dir }}"
  tags:
    - deploy

- name: Write the configuration file
  template: src=templates/config.txt.j2 dest="{{ xmr_stak_bin_dir }}/config.txt"
  tags:
    - deploy

- name: Switch tsocks configuration file for external
  command: "killall autossh"
  tags:
    - remoteproxy

- name: Switch tsocks configuration file for external
  template: src=templates/tsocks-remote.conf.j2 dest="/etc/tsocks.conf"
  tags:
    - remoteproxy

- name: Switch tsocks configuration file for internal
  template: src=templates/tsocks-local.conf.j2 dest="/etc/tsocks.conf"
  tags:
    - localproxy

- name: Switch Remoteproxy Server
  template: src=templates/tsocks-local.conf.j2 dest="/etc/tsocks.conf"
  tags:
    - localproxycn

- name: Restart Remoteproxy Server
  script: scripts/localproxycn.sh start
  tags:
    - localproxycn

- name: Switch Remoteproxy Server
  template: src=templates/tsocks-local.conf.j2 dest="/etc/tsocks.conf"
  tags:
    - localproxyus

- name: Restart Remoteproxy Server
  script: scripts/localproxyus.sh start
  tags:
    - localproxyus

- name: Check Server Status
  shell: "ps -eo pid,ppid,cmd,%cpu --sort=-%cpu | head -2"
  tags:
    - check

- name: Stop Stak
  script: scripts/stopstak.sh start
  tags:
    - stopstak

- name: Start Stak20
  script: scripts/xmrstak20.sh start
  tags:
    - startstak20

- name: Delete CPU configuration file
  file:
    path: "{{ xmr_stak_bin_dir }}/cpu.txt"
    state: absent
  tags:
    - startstak22

- name: Start Stak22
  script: scripts/xmrstak22.sh start
  tags:
    - startstak22
